import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Health' }).click();
  await page.getByRole('button', { name: 'Enter Mode' }).click();
  await page.getByRole('textbox', { name: 'Row 1, Column 1' }).click();
  await page.getByRole('textbox', { name: 'Row 1, Column 1' }).fill('1');
  await page.getByRole('textbox', { name: 'Row 1, Column 3' }).dblclick();
  await page.getByRole('textbox', { name: 'Row 1, Column 3' }).fill('2');
  await page.getByRole('textbox', { name: 'Row 1, Column 5' }).click();
  await page.getByRole('textbox', { name: 'Row 1, Column 5' }).click();
  await page.getByRole('textbox', { name: 'Row 1, Column 5' }).fill('3');
  await page.getByRole('textbox', { name: 'Row 1, Column 8' }).dblclick();
  await page.getByRole('textbox', { name: 'Row 1, Column 8' }).fill('4');
  await page.getByRole('textbox', { name: 'Row 3, Column 7' }).click();
  await page.getByRole('textbox', { name: 'Row 3, Column 7' }).fill('5');
  await page.getByRole('textbox', { name: 'Row 3, Column 9' }).click();
  await page.getByRole('textbox', { name: 'Row 3, Column 9' }).fill('6');
  await page.getByRole('textbox', { name: 'Row 6, Column 8' }).click();
  await page.getByRole('textbox', { name: 'Row 6, Column 8' }).fill('7');
  await page.getByRole('textbox', { name: 'Row 8, Column 8' }).click();
  await page.getByRole('textbox', { name: 'Row 8, Column 8' }).fill('8');
  await page.getByRole('textbox', { name: 'Row 9, Column 8' }).click();
  await page.getByRole('textbox', { name: 'Row 9, Column 8' }).fill('9');
  await page.getByRole('textbox', { name: 'Row 9, Column 5' }).click();
  await page.getByRole('textbox', { name: 'Row 9, Column 5' }).fill('8');
  await page.getByRole('textbox', { name: 'Row 9, Column 2' }).click();
  await page.getByRole('textbox', { name: 'Row 9, Column 2' }).fill('7');
  await page.getByRole('textbox', { name: 'Row 8, Column 3' }).click();
  await page.getByRole('textbox', { name: 'Row 6, Column 2' }).click();
  await page.getByRole('textbox', { name: 'Row 6, Column 2' }).fill('6');
  await page.getByRole('textbox', { name: 'Row 4, Column 2' }).click();
  await page.getByRole('textbox', { name: 'Row 4, Column 2' }).fill('5');
  await page.getByRole('textbox', { name: 'Row 3, Column 2' }).click();
  await page.getByRole('textbox', { name: 'Row 3, Column 2' }).fill('4');
  await page.getByRole('textbox', { name: 'Row 4, Column 5' }).click();
  await page.getByRole('textbox', { name: 'Row 5, Column 5' }).click();
  await page.getByRole('textbox', { name: 'Row 5, Column 5' }).fill('9');
  await page.getByRole('textbox', { name: 'Row 5, Column 7' }).click();
  await page.getByRole('button', { name: 'Solve' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Solution Explanation').click();
});